name: Purephysica
safe: true
lsi: false

title: Purephysica

markdown: kramdown
redcarpet:
  extensions: ["autolink", "no_intra_emphasis", "fenced_code_blocks", "autolink", "strikethrough", "superscript", "with_toc_data", "tables"]
highlighter: rouge

url: "https://purephysica.github.io"